### ISSUE TITLE
Is there a secure way to add a WHERE clause form to list pages?

### ISSUE THREAD

**Issue by it-all** [it-all/Spaghettify#4]
I'd like to give admins the ability to flexibly filter a list view by adding a form above with simply a text field, which will then be entered as the WHERE clause in the query, but it seems it would be vulnerable to SQL injection unless a [complicated] parse is performed.

**Comment by ircmaxell** [comment]
Don't allow arbitrary expressions. Simply force it to be key/value (the name of the text field is the key, and the value is what the user enters). 

Then check the key is an apropriate field on the table (meaning check that it's exactly the same as the name of a searchable field). If so, let it through. If not, fail it.

Then simply bind the user input to the query just like any other query. 

No need to create complex parsers if all you're doing is letting them "search" specific fields.
